# Generated by Django 2.1.4 on 2019-01-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190119_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphered_answer', models.BigIntegerField(blank=True, null=True)),
                ('public_key_x', models.BigIntegerField(blank=True, null=True)),
                ('public_key_y', models.BigIntegerField(blank=True, null=True)),
                ('private_key', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='public_key_x',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='public_key_y',
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
    ]
