# Generated by Django 2.1.4 on 2019-01-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190119_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Question'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Choice'),
        ),
    ]
