# Generated by Django 2.1.4 on 2019-01-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190119_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='private_key_0',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='private_key_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='public_key_x_0',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='public_key_x_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='public_key_y_0',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='public_key_y_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
