# Generated by Django 2.1.4 on 2019-01-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190119_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='private_key_0',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='private_key_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='public_key_x_0',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='public_key_x_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='public_key_y_0',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='public_key_y_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ciphered_answer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='private_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='public_key_x',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='public_key_y',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
