# Generated by Django 2.1.4 on 2019-01-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choice_ciphered_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='ciphered_answer',
            new_name='ciphered_answer_0',
        ),
        migrations.AddField(
            model_name='choice',
            name='ciphered_answer_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
