# Generated by Django 2.1.4 on 2019-01-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_vote_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenDigits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_x', models.CharField(blank=True, max_length=150, null=True)),
                ('public_key_y', models.CharField(blank=True, max_length=150, null=True)),
                ('private_key', models.CharField(blank=True, max_length=150, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(blank=True, max_length=300, null=True)),
                ('vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Vote')),
            ],
        ),
        migrations.AddField(
            model_name='chosendigits',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Receipt'),
        ),
    ]
