# Generated by Django 2.1.4 on 2019-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_chosendigits_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosendigits',
            name='chosen_answer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
